CAPTCHA_PAGE = 'human-verification'
FAILED = 'FAILED'
NEW = 'NEW'
IN_PROGRESS = "IN_PROGRESS"
DOWNLOADED = "DOWNLOADED"
SUCCESS = "SUCCESS"
UNKNOWN = "Unknown"
INVALID_GALLERY_URL = "INVALID_GALLERY_URL"